services:
  db:
    image: postgres:17
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      TZ: "UTC"
    ports:
      - "5432:5432"
    networks:
      - matcha-network
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  client:
    build:
      context: client
    env_file:
      - .env
    networks:
      - matcha-network
    volumes:
      - static-data:/usr/src/app

  backend:
    build:
      context: server
    env_file:
      - .env
    networks:
      - matcha-network
    depends_on:
      db:
        condition: service_healthy

  # webserver:
  #   build:
  #     context: services/webserver
  #   networks:
  #     - matcha-network
  #   volumes:
  #     - static-data:/next
  #   env_file:
  #     - .env
  #   ports:
  #     - 8080:80
  #     - 8443:443
  #   depends_on:
  #     - client
  #     - backend

networks:
  matcha-network:
    driver: bridge

volumes:
  db-data:
  static-data: